source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'CDAUtils_Example', :exclusive => true do
  pod "CDAUtils", :path => "../"
end

target 'CDAUtils_Tests', :exclusive => true do
  pod "CDAUtils", :path => "../"

  pod 'Kiwi'
end
